### PR TITLE
Sync with vanilla repo

### PR DESCRIPTION
**Pull request by AgentRev**
There, I did the bulk for you. I have not modified or removed any feature or option from your version.

Needs testing to make sure everything is fine. There are errors on my end because I don't have your donator config files and stuff, so you'll have to do it.

### CODE REVIEW

**Comment by AgentRev** [comment]
Hang on, I can fix those, just gimme a couple mins. The Tortoise merging UI is not very good for dealing with duplicates from different commits, I'm gonna WinMerge between your repo and mine.

**Comment by AgentRev** [comment]
There. The mag repack thing was due to a Windows vs Linux fight, Linux paths are case-sensitive but Win paths aren't. Since Git is originally made for Linux, it was like "I win" and Windows is like "wtf"

I reorganized the rifles so they are in the same order as vanilla, it will make later merging easier if needed. I removed the DLC comments since they are superfluous.

**Comment by LouDnl** [comment]
Thanks Rev.
Yea only client/functions/updateTeamKiller.sqf left then :) As I lock players to Independent aswell to stop quick teamswitching to see opfor or blufor positions.

**Comment by AgentRev** [comment]
I removed the thing in updateTeamKiller.sqf because it doesn't do anything, that file already locks players out of Blufor and Opfor by default, it triggers after 2 teamkills are made. It was a failed fix attempt for another problem I think.

Your indie lock code is already in there: https://github.com/AgentRev/LouDnl_A3Wasteland.Altis/blob/36dbc3f798e6e546b539c419d085f3502142f3b8/client/functions/firstSpawn.sqf#L185-L201

**Comment by LouDnl** [comment]
Ok cool thanks! So how would I go about doing this myself? I see that you are pulling in all the commits but the changed files are less then all the commits.
I need to do Stratis too.

**Comment by LouDnl** [comment]
Ah I see that I really put in the addition to updateTeamKiller.sqf. What I did was when someone gets banished from OpFor and BluFor that they automaticly get locked to Independent.

**Comment by AgentRev** [comment]
The fact that the player is marked as a teamkiller prevents him from joining Blufor and Opfor, there is no reason to explicitly lock them to independent on top of that, the teamkiller code already makes sure he can only join as independent.

**Comment by AgentRev** [comment]
The only thing that code does is the following:

With the code, if you do "Unlock Team Kill" on a player from the admin panel, he won't be able to leave Indie unless you also do "Unlock Team Switch", regardless of the original team he was on.

Without the code, if you do "Unlock Team Kill" on a player from the admin panel, he will be able to rejoin any team, then the game will later lock him that team.

**Comment by LouDnl** [comment]
Thanks for the explanation. I'm going to merge this pull request.
Now for me to start learning how to do this myself so I can fix my Stratis repo too.

**Comment by AgentRev** [comment]
As for Stratis, well the same exact thing will have to be done. I can do it too, because I'm not sure you'll be able to do it without getting lost. Merging desynced repos is quite tougher than a regular merge.

All the commits are pulled by the merging process so as to make sure that both repos share the same history, which makes it easier when it comes to merging again later as Git knows what doesn't need to be overwritten and what can cause conflicts.

**Comment by LouDnl** [comment]
I would be very gratefull if you would do this for our Stratis repo too. But i'd love to know how to do it myself too.

**Comment by LouDnl** [comment]
Worked out Stratis myself with SourceTree!

**Comment by AgentRev** [comment]
Nice :) I was planning to do it for you this weekend, but I guess this outcome is better for both of us

**Comment by LouDnl** [comment]
All works fine, only have 1 problem lol. Theres two magrepack folders. Forgot to unselect it when merging. How do I fix this?
https://github.com/LouDnl/ArmA3_Wasteland.Stratis/tree/NL-United/addons

**Comment by LouDnl** [comment]
Nvm fixed it

**Pull request merged**
